name: quizu
description: A new Flutter challenge.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  shared_preferences: ^2.0.15
  http: ^0.13.5
  provider: ^6.0.3
  country_code_picker: ^2.0.2
  pin_code_fields: ^7.4.0
  flutter_spinkit: ^5.1.0
  phone_number: ^1.0.0
  avatar_glow: ^2.0.2
  share_plus: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.10+1

flutter_native_splash:
    background_image: "assets/images/s.png"


flutter:

  uses-material-design: true

  assets:
    - assets/images/flag.png
    - assets/images/logo.png
    - assets/images/i1.png
    - assets/images/i2.png
    - assets/images/i3.png
    - assets/images/sad.png
    - assets/images/user.png
    - assets/images/trophy.png


  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal-Regular.ttf
    - family: QICONS
      fonts:
        - asset: assets/icons/QIcons.ttf